import pygal  
from pygal.style import NeonStyle                                                   
line_chart = pygal.HorizontalBar(
										#title='External contribution analysis',
										title_font_size=24, fill=True,
										style=NeonStyle,
										#spacing=500,
										#margin=50,
										x_label_rotation=30,
										truncate_legend=65,
										pretty_print=True,
										width=2000,
										height=2000,
										value_font_size=26,
										legend_font_size=24,
										label_font_size=20,
										tooltip_font_size=28
										)
#line_chart.title = 'External contribution analysis (in numbers)'
line_chart.x_labels = ['akka',
'devtools',
'ProjectTemplate',
'stat-cookbook',
'hiphop-php',
'knitr',
'shiny',
'folly',
'mongo',
'doom3.gpl',
'phantomjs',
'TrinityCore',
'MaNGOS',
'bitcoin',
'mosh',
'xbmc',
'http-parser',
'beanstalkd',
'redis',
'ccv',
'memcached',
'openFrameworks',
'libgit2',
'redcarpet',
'libuv',
'SignalR',
'SparkleShare',
'plupload',
'mono',
'Nancy',
'ServiceStack',
'AutoMapper',
'RestSharp',
'ravendb',
'MiniProfiler',
'storm',
'elasticsearch',
'ActionBarSherlock',
'facebook-android-sdk',
'clojure',
'CraftBukkit',
'netty',
'android',
'node',
'jquery',
'html5-boilerplate',
'impress.js',
'd3',
'chosen',
'Font-Awesome',
'three.js',
'foundation',
'symfony',
'CodeIgniter',
'php-sdk',
'zf2',
'cakephp',
'ThinkUp',
'phpunit',
'Slim',
'django',
'tornado',
'httpie',
'flask',
'requests',
'symfony',
'reddit',
'boto',
'django-debug-toolbar',
'Sick-Beard',
'django-cms',
'rails',
'homebrew',
'jekyll',
'gitlabhq',
'diaspora',
'devise',
'blueprint-css',
'octopress',
'vinc.cc',
'paperclip',
'compass',
'finagle',
'kestrel',
'flockdb',
'gizzard',
'sbt',
'scala',
'scalatra',
'zipkin',
'Bukkit',
'Overall statistics']
line_chart.add('External pull request accepted',
[

])
line_chart.add('External pull request submitted',
[

])
line_chart.render_to_file('m2_chart_numbers_pr.svg')